return {
    metadata = {
        name = "Base WM",
        author = "Andre Wagner",
        link = {
            "https://github.com/andrenho/customwm"
        }
    },

    resources = {

        images = {
            main = {
                format = "png",
                base64 = "iVBORw0KGgoAAAANSUhEUgAAAJAAAAEoCAMAAACAdogmAAADAFBMVEUbR0fJ9fNnfWEAnp4AAACRj4/V19kAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADXUa/+AAAAA3RSTlP//wDXyg1BAAAAD3RFWHRTb2Z0d2FyZQBHcmFmeDKgolNqAAAASGNyTmcAAAACMD8AAAACQE8AAAACUF8AAAACYG8AAAACcH8AAAACgI8AAAACkJ8AAAACoK8AAAACsL8AAAACwM8AAAAC0N8AAAAC4O+6mu6bAAACOklEQVR4nO3a0W6CMBhA4TqZ7//IiyFRYG1Pf0JHcedctgJfEDYQ0tdgpbMB2wRRgihBlCBKECWIEkRdAXSrlGqT8SUyWz8VlFpB92KpMhdfQtCRoNS9KKjzQZ1uYVDwCyjN1FYkSNCFQetTbATQauiDQNsd3QJafLoDaLOaJtD704IE3bfXC6eDyputgN78MUDZcUEI+nX16n97Qf8ZNJ8J6/PiVWG4MlNdUeMeumV/KDm2+aqpEfTcm91B0WNIkCBBggQJEiRIkCBBgnqBUuEW7mCQN4oEuvAxJEiQIEGCBAkSJEiQoCNA4TcoowVBhXw5d1BQ8UFv7SHwriXaQLtX3wl0boIoQZQgShAliBJECaIEUYIoQZQgShAliBJECaIEUYKoDOhRaapNxpeYBgNNraDvYlNlLr6EoCNBU/eioM4H9fQIg4JfQGmmtiJBgi4MWp9iI4CWQ+mDQNsd3QJafLoDaLnFVtBro4IEbS5CRgCVN1sBza8IjAPKjgtC0OqNjwFA+WFBgv4INP9dfuRv7wrDlZnqihr30CP7Q8mxzVdNjaDn3uwOih5DggQJEiRIkCBBggQJEtQLNBVu4Q4GeaNIoAsfQ4IECRIkSJAgQYIECToCFH6DMloQVMiXcwcFFR/01h4C71qiDbR79Z1A5yaIEkQJogRRgihBlCBKECWIEkQJogRRgihBlCBKECWIEkQJogRRgihBlCBKECWIEkQJogRRgihBlCBKECWIEkQJogRRw4F+AMqOhA+G3zh7AAAAAElFTkSuQmCC",
                slices = {
                    close = { 96, 24, 24, 24 },
                }
            },
        },

        fonts = {
            fixed = {
                format = "x11",
                name = "-misc-fixed-bold-r-normal--14-130-75-75-c-70-iso8859-1",
            }
        },

    },

    window = {
        padding = { 24, 3, 3, 3 },
        starting_pos = "random",
        on_expose = function(window, area)
            window:draw_rectangle({ 0, 0, 220, 24 } , "#bbbbbb", true)
            -- window:draw_line({ 0, 0 }, { 20, 20 }, "#ff0000")
            -- window:draw_image({ 0, 0 }, "main.close")
            window:write({ 0, 0 }, window:name(), "fixed", "#ff8800", { size = { 220, 24 }, halign = "center", valign = "bottom" })
        end
    }
}
