@startuml

class Options

rectangle theme {
    package lua_scripts <<Database>> {
    }
    class Theme
    lua_scripts -> Theme
    note right of Theme
        Loads user-provided
        theme file
    end note
}

class Window <to_lua>

rectangle windowmanager {
    class WindowManager <to_lua>
    class ParentWindow
    class WMEvents {
        +run()
    }
    WindowManager -> "1..n" ParentWindow
    ParentWindow -up-|> Window
    WindowManager .left. WMEvents
}

rectangle graphics {
    abstract class Graphics
    abstract class Pencil
    abstract class XGraphics

    Graphics <|-- XGraphics
    Graphics <|-- WaylandGraphics

    XGraphics <|-- XlibGraphics
    XGraphics <|-- XOpenGLGraphics

    Pencil <|-- XlibPencil
    Pencil <|-- OpenGLPencil

    OpenGLPencil .. OpenGLManager
}

windowmanager -up-> Theme
WindowManager --> Graphics
Window --> Pencil

@enduml