return {
    metadata = {
        name = "Base WM",
        author = "Andre Wagner",
        link = {
            "https://github.com/andrenho/customwm"
        }
    },

    resources = {

        images = {
            main = {
                format = "png",
                base64 = "iVBORw0KGgoAAAANSUhEUgAAAJAAAAEoCAMAAACAdogmAAADAFBMVEUbR0fJ9fNnfWEAnp4AAACRj4/V19n/AP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABtbW2qqqr///8YfVZ4AAAAA3RSTlP//wDXyg1BAAAAD3RFWHRTb2Z0d2FyZQBHcmFmeDKgolNqAAAASGNyTmcAAAACMD8AAAACQE8AAAACUF8AAAACYG8AAAACcH8AAAACgI8AAAACkJ8AAAACoK8AAAACsL8AAAACwM8AAAAC0N8AAAAC4O+6mu6bAAACgklEQVR4nO3c226DMBBFUZPQ9P//uIpQQ6AeHw+y8ZDu/VRxXSJAIaCk23QLVRoN2AdIBUgFSAVIBUgFSAVIdQXQVCiVRvrnyKx9KCjVgu5mqTDOPweglqDUPS+o806dJjfI+QFYY0oLAgTowqDtIRYBtBn0QaD9hq4BvU3dAbRbTBVonRoQoPv+emE4yF5tAbTyY4CywwFJ0J+rV/7bA/rPoOVI2B4Xr4zBhTHFBVVuoSn7RUnblqumStBza3YHefchQIAAAQIECBAgQIAAAeoFSsYtXGMQN4oKdOF9CBAgQIAAAQIECBAgQC1A7jcovTlBRrycGxRkPugtPQQ+NEcd6PDiO4HGBkgFSAVIBUgFSAVIBUgFSAVIBUgFSAVIBUgFSAVIBUgFSJUBPQrNpZH+OeZgoLkW9GU2F8b55wDUEjR3zwvqvFPPDzfI+QFYY0oLAgTowqDtIRYB9D4ofRBov6FrQG9TdwC9r7EW9FopIEC7i5AIIHu1BdDyikAcUHY4IAnavPERAJQfDAjQSaDlvPzI394Zgwtjiguq3EKP7BclbVuumipBz63ZHeTdhwABAgQIECBAgAABAgSoF2g2buEag7hRVKAL70OAAAECBAgQIECAAAFqAXK/QenNCTLi5dygIPNBb+kh8KE56kCHF98JNDZAKkAqQCpAKkAqQCpAKkCqeKBvI0CAGoA2v0+Y/7HC80G/COPXEweA0uoJAkqbv4aCXo4TPeIoE7+/eT7odrpHnofO9ugT48mey22haPtQtKMs2nko3Jk65v+y3+migNYJA4CGBEiCRq3YCpAKkAqQCpAKkAqQCpAKkAqQCpAKkAqQCpAKkAqQKhzoB5wCjdQQUdxMAAAAAElFTkSuQmCC",
                slices = {
                    close = { 96, 24, 24, 24 },
                    square = { 0, 240, 24, 24 },
                    x = { 24, 240, 24, 24 },
                }
            },
        },

        fonts = {
            fixed = {
                format = "x11",
                name = "-misc-fixed-bold-r-normal--14-130-75-75-c-70-iso8859-1",
            }
        },

    },

    window = {
        padding = { 24, 3, 3, 3 },
        starting_pos = "random",
        on_expose = function(window, area)
            window:draw_rectangle({ 0, 0, window:area().w + 6, 24 } , "#bbbbbb", true)
            -- window:draw_line({ 0, 0 }, { 20, 20 }, "#ff0000")
            -- window:draw_image({ 0, 0 }, "main.close")
            window:write({ 0, 0 }, window:name(), "fixed", "#884400", { size = { window:area().w + 6, 24 }, halign = "center", valign = "center" })
            window:draw_image({ 0, 0 }, "main.square")
            window:draw_image({ 0, 0 }, "main.x")
        end
    }
}
