name: Build & Check leaks
on:
  - pull_request
jobs:
  build:
    name: Build and test for leaks
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get clean
          sudo apt-get update
          sudo apt-get install -y libx11-dev libxft-dev libz3-dev libfreetype-dev libglew-dev mesa-common-dev libglm-dev cmake g++ valgrind
      - name: Run CMake
        run: mkdir ${{ github.workspace }}/build && cd ${{ github.workspace }}/build && cmake ${{ github.workspace }}
      - name: Build application
        run: make -C ${{ github.workspace }}/build
      - name: Look for leaks
        run: cd ${{ github.workspace }}/build && valgrind --leak-check=full --show-leak-kinds=all --suppressions=../customwm.supp --gen-suppressions=all -- ./customwm -b dummy -v -x