name: Release new version
on:
  - pull_request
jobs:
  build:
    name: Generate package and release it
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build package
        run: cd ${{ github.workspace }} && ./makedist.sh
      - name: Get version
        run: |
          VER=$(cat ${{ github.workspace }}/PRJ_VERSION
          echo "VERSION=$VER" >> $GITHUB_ENV
          echo $GITHUB_ENV
      - name: Create release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: ${{ github.workspace }}/customwm-*.tar.bz2
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
          prerelease: true
          tag: "v${{ env.VERSION }}"
          commit: "${{ github.ref }}"