name: Build & Check leaks
on:
  pull_request:
    types: [opened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y libx11-dev libz3-dev libfreetype-dev cmake g++ valgrind
      - run: mkdir ${{ github.workspace }}/build && cd ${{ github.workspace }}/build && cmake ..
      - run: make -C ${{ github.workspace }}/build